# Generated by Django 4.0.3 on 2022-03-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('category', models.TextField()),
                ('requisitos', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='Empleo1')),
                ('titulo_imagen', models.CharField(max_length=100)),
                ('oferta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleo_bajo_nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('category', models.TextField()),
                ('requisitos', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='Empleo3')),
                ('titulo_imagen', models.CharField(max_length=100)),
                ('oferta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleo_profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('category', models.TextField()),
                ('requisitos', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='Empleo2')),
                ('titulo_imagen', models.CharField(max_length=100)),
                ('oferta', models.TextField()),
            ],
        ),
    ]
