# Generated by Django 4.0.3 on 2022-03-16 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_empleosti', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleo_bajo_nivel',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='empleo_bajo_nivel',
            name='titulo_imagen',
        ),
        migrations.RemoveField(
            model_name='empleo_profesional',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='empleo_profesional',
            name='titulo_imagen',
        ),
    ]
