# Generated by Django 4.0.3 on 2022-03-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_empleosti', '0002_remove_empleo_bajo_nivel_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleo',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='empleo',
            name='titulo_imagen',
        ),
    ]
